# Generated by Django 4.2 on 2023-09-20 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='eg.Database management System Expert', max_length=200)),
                ('job_description', models.TextField()),
                ('job_role', models.CharField(help_text='Backend Developer', max_length=100)),
                ('job_location', models.CharField(choices=[('H', 'Hybrid'), ('R', 'Remote'), ('Onsite', 'On site')], max_length=100)),
                ('job_responsibilities', models.TextField(blank=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('NS', 'National Service'), ('C', 'Contract'), ('In', 'Internship')], max_length=30)),
                ('expired', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
