# Generated by Django 4.2 on 2023-09-13 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('school', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('index_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('1', 'level 100'), ('2', 'level 200'), ('3', 'level 300'), ('1', 'level 400')], help_text='your student level', max_length=15)),
                ('is_student', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students_course', to='course.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students_school', to='school.school')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='The name of the organization', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisation_logo/%Y/%m/%d/')),
                ('is_organization', models.BooleanField(default=True)),
                ('industry_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_types', to='industry.type')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
    ]
