# Generated by Django 4.2 on 2023-09-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': 'Docs', 'verbose_name_plural': 'Docs'},
        ),
    ]
